apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  ignoreDifferences:
    - group: ''
      kind: 'Secret'
      name: jenkins
      jsonPointers:
        - /data
    - group: ''
      kind: 'SealedSecret'
      name: jenkins
      jsonPointers:
        - /data
  destination:
    namespace: 'jenkins-ns'
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: jenkins
      repoURL: https://charts.jenkins.io
      targetRevision: 5.6.1
      helm:
        releaseName: jenkins
        valueFiles:
          - $values/values/jenkins/sealed-secret-jenkins.yml
    - repoURL: 'https://github.com/TheUnixRoot/kubernetes_as_code.git'
      targetRevision: main
      ref: values
  project: default
