apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: replicaset
spec:
  destination:
    name: ''
    namespace: 'context-test-1-ns'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'applications/replicaset'
    repoURL: 'https://github.com/TheUnixRoot/kubernetes_as_code.git'
    targetRevision: HEAD
  project: default
