apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-rollout
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: 'context-test-1-ns'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'applications/guest-book'
    repoURL: 'https://github.com/TheUnixRoot/kubernetes_as_code.git'
    targetRevision: HEAD
  project: default
