apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: temperaturas
  annotations:
    kubernetes.io/ingress.class: nginx # https://github.com/nginxinc/kubernetes-ingress/issues/1274
spec:
  rules:
    - host: www.temperaturas.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: temperaturas-frontend-service-active
                port:
                  number: 3000