apiVersion: v1
kind: Service
metadata:
  name: temperaturas-frontend-service-active
spec:
  type: ClusterIP
  ports:
    - name: service-guestbook
      port: 3000
      targetPort: http-server
  selector:
    app: temperaturas