apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-testweb
  labels:
    app: web
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: iesgn/test_web:latest
          name: contenedor-nginx
          ports:
            - name: http
              containerPort: 80