apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  destination:
    namespace: 'argocd'
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: argo-rollouts
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 2.37.7
  project: default
