apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: redis-disconnected
  labels:
    app: redis-disconnected
    tier: backend
spec:
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {duration: 10}
  replicas: 1
  selector:
    matchLabels:
      app: redis-disconnected
      tier: backend
  template:
    metadata:
      labels:
        app: redis-disconnected
        tier: backend
    spec:
      containers:
        - name: contenedor-redis
          image: redis
          ports:
            - name: redis-server
              containerPort: 6379