apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: 'context-test-1-ns'
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 62.7.0
      helm:
        skipCrds: true
  project: default
