apiVersion: v1
kind: Service
metadata:
  name: temperaturas-frontend-service-active
spec:
  type: ClusterIP
  ports:
    - name: temperaturas-service-active-port
      port: 3000
      targetPort: http-server
  selector:
    app: temperaturas
    tier: frontend