apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bd-passwords
  namespace: context-test-1-ns
spec:
  encryptedData:
    bd_password: AgA1pyv7AoNQgj5YVYl1aRU3C4I7TbRLpVUKFM+eQJ7B3YpkctB5Kxjd8s/nmGPq6qFUqPYwLghyx/bj0o1OwVwqqKdxHRW0Ff+SDsB/KdG6fMSmqyDf/Kr8r2k/BU+5HXwXFHouqie0zqgXxFkqQNbOeDXwpCE3natTjgQDXZLpw55JUlTMau8EJUlSDzAVnLZi5CW481kQigyhINqyU0pitz6a2MEfcLZxzqiHkBq0LYq8+SZu3N9ROKidP9az8Exxgd7MnKl/23lu+mytLny+x+u8qIQYYGTtL6UjHODLWySMy4UGSOH0g6OZXbXPbB9xEUiHy7jK7kqG3BdAlXY6rda7NPtrXyijEJuErkBBoFgVFyJHzTAmEmCmks4KekzrpLDuJB1HnfWGXBdGw30dnI0l/p7963hO8b9FDSeMfNPMFHaqY0n95Pyh9gVWV+oUZCCFIvnMLTa60QKUpWpBRIcaiyesvQxcSrhQFPlPLTUGKPdHXHz49fpsbNi1jzu1RgAb6ZqPm6b+lY8U0kYSNB/4Y/aAGUxn3w/yc6yhSfKPKONMEqYV+FFCLokjsc4Dtw51CksfuZVuyYIGYZOd9kRSvmtz+ZkmqsFRWANFV7U1R3OxcCWhMwUwqbALxJvqaE9aAIs9MC8eSkiGadT7C22UhyCFQ2QSw9hbYbpPNqpZKk3QyE5fFl+HG+yVlGs0B836kcHuhwE=
    bd_rootpassword: AgAGJaRjGvD0ColwiA1NdfmeAeWSDV22iVaA5Wa3wb0LqeCzMPUrLL9TKki+AwLFdNx/BnlDffgA51huJrIHeix+jDKag7e9SVNnJUhfxk68BOs0rx9bsdpNWTLs7zgKQW/DK38fxgjq92Ly5rtR+FDexQ7Ud5EqLr84plh5mTIw7/lbEQwq9YC1CryUU7Tl/yt0RWn/JU9GEdOolvtzAT+31feBwoenjCkPRFb8OU3qXtivgvYFWAkXttHwB+6PxvHBC491TWbuy5C5AMDufjpYZ1sB5QOfJveMNCH4LzcxpPQahll1VG00qIyPIVq5McTX2M1KL223LHzl+h3ARfEYx07pPtjYBLY4ZRVeqzNdPQPgn37aVJ/y98DDdrjHliUocdtQAI757s25CexAR7ZUSWnswHtuQPVEF4QlENQUqTTHhxycOeumHKKs9XyDm2Fn1k5Q/RChRKiP2IYl6cNiat3RVsD5zs3FtIZekDQ1+cdLnfY0sr1JutKopf7NqXnBSwK0HrRU6evXzROSg5hZzD6wwUEXMpvNqPrfERCV6ECf5xN5QJPiKZX6apAib/p0czFCeTc3kZ/GBcNWbim5GApx8PgYFcXr9ibbfsagjVBXoHbAcWhMf65kX86tqQ51iyWdPfjUqF36Q3qGztht56P7wO0bGvB1Sw9BpvLpf+3SORVEgi82jaDaiJBGP4luGcaM22XrPvg=
  template:
    metadata:
      creationTimestamp: null
      name: bd-passwords
      namespace: context-test-1-ns
    type: Opaque